// Script para criar tabelas faltantes no Supabase
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://rwpmtuohcvnciemtsjge.supabase.co';
const SERVICE_ROLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3cG10dW9oY3ZuY2llbXRzamdlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTMxMzU3NiwiZXhwIjoyMDgwODg5NTc2fQ.d1c1WPyOtRBkJ1E3DwYUtoQ7FUJ0iSGA14dokqx_8ww';

async function createMissingTables() {
  const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

  console.log('Creating missing tables...\n');

  // SQL para criar as tabelas faltantes
  const createAgendaEventsSQL = `
    CREATE TABLE IF NOT EXISTS agenda_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      event_type VARCHAR(50) DEFAULT 'other',
      status VARCHAR(50) DEFAULT 'scheduled',
      start_date TIMESTAMPTZ,
      end_date TIMESTAMPTZ,
      all_day BOOLEAN DEFAULT false,
      location_id BIGINT REFERENCES locations(id),
      project_id BIGINT REFERENCES projects(id),
      user_id BIGINT REFERENCES users(id),
      color VARCHAR(20),
      priority VARCHAR(20) DEFAULT 'medium',
      created_by BIGINT REFERENCES users(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );

    ALTER TABLE agenda_events ENABLE ROW LEVEL SECURITY;

    CREATE POLICY IF NOT EXISTS "View agenda events" ON agenda_events FOR SELECT
      USING (auth.role() = 'authenticated');

    CREATE POLICY IF NOT EXISTS "Manage agenda events" ON agenda_events FOR ALL
      USING (auth.role() = 'authenticated');
  `;

  const createUserProjectsSQL = `
    CREATE TABLE IF NOT EXISTS user_projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
      role VARCHAR(50) DEFAULT 'member',
      permissions JSONB DEFAULT '{}',
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(user_id, project_id)
    );

    ALTER TABLE user_projects ENABLE ROW LEVEL SECURITY;

    CREATE POLICY IF NOT EXISTS "View user projects" ON user_projects FOR SELECT
      USING (auth.role() = 'authenticated');

    CREATE POLICY IF NOT EXISTS "Manage user projects" ON user_projects FOR ALL
      USING (auth.role() = 'authenticated');
  `;

  console.log(
    'NOTE: You need to run this SQL manually in Supabase Dashboard SQL Editor:'
  );
  console.log('\n--- SQL FOR agenda_events ---');
  console.log(createAgendaEventsSQL);
  console.log('\n--- SQL FOR user_projects ---');
  console.log(createUserProjectsSQL);

  // Tentar inserir um registro de teste para verificar se as tabelas existem
  console.log('\n--- Checking if tables exist ---');

  const { error: agendaCheck } = await supabase
    .from('agenda_events')
    .select('*', { count: 'exact', head: true });

  if (agendaCheck) {
    console.log('❌ agenda_events: NOT EXISTS -', agendaCheck.code);
  } else {
    console.log('✅ agenda_events: EXISTS');
  }

  const { error: userProjCheck } = await supabase
    .from('user_projects')
    .select('*', { count: 'exact', head: true });

  if (userProjCheck) {
    console.log('❌ user_projects: NOT EXISTS -', userProjCheck.code);
  } else {
    console.log('✅ user_projects: EXISTS');
  }
}

createMissingTables().catch(console.error);
