"""Add compatibility fields for frontend project creation

Revision ID: 003
Revises: 002
Create Date: 2025-01-15 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Adicionar campos de compatibilidade para projetos
    op.add_column('projects', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Float(), nullable=True, default=0.0))
    op.add_column('projects', sa.Column('responsibleUserId', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remover campos de compatibilidade
    op.drop_column('projects', 'responsibleUserId')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'title')

    # ### end Alembic commands ###

